-- ============================================================================
-- AZURE-001: Synthetic seed data - CUSTOMER_MASTER
--
-- 20 customers total:
--   CUST-000001 .. CUST-000017  clean records
--   CUST-000018 .. CUST-000020  deliberate BUSINESS-QUALITY defects
--
-- All defect rows are technically insertable (no PK/NOT NULL/CHECK
-- constraint violations) - they are the kind of bad data a real source
-- system produces and that a downstream Databricks DQ layer is expected
-- to catch, not something the Oracle engine would ever reject.
-- ============================================================================

-- Clean records
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000001', 'Johanna Berg', 'RETAIL', 'DE-TAX-88213', 'DE', DATE '2021-03-11', 'LOW', 'ACTIVE', DATE '2026-08-30');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000002', 'Marcus Whitfield', 'RETAIL', 'GB-TAX-40217', 'GB', DATE '2020-07-22', 'MEDIUM', 'ACTIVE', DATE '2026-08-30');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000003', 'Nordholm Logistics AG', 'COMMERCIAL', 'CH-TAX-10093', 'CH', DATE '2019-11-04', 'MEDIUM', 'ACTIVE', DATE '2026-08-29');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000004', 'Elena Marchetti', 'RETAIL', 'IT-TAX-77452', 'IT', DATE '2022-01-18', 'LOW', 'ACTIVE', DATE '2026-08-31');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000005', 'Union Freight Partners Ltd', 'COMMERCIAL', 'GB-TAX-55810', 'GB', DATE '2018-05-09', 'HIGH', 'ACTIVE', DATE '2026-08-28');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000006', 'Sato Retail Holdings', 'COMMERCIAL', 'JP-TAX-30021', 'JP', DATE '2020-09-14', 'MEDIUM', 'ACTIVE', DATE '2026-08-30');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000007', 'Priya Nair', 'RETAIL', 'SG-TAX-66740', 'SG', DATE '2023-02-27', 'LOW', 'ACTIVE', DATE '2026-09-01');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000008', 'Dubois Immobilier SARL', 'COMMERCIAL', 'FR-TAX-19934', 'FR', DATE '2019-06-30', 'MEDIUM', 'ACTIVE', DATE '2026-08-27');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000009', 'Liam O''Connor', 'RETAIL', 'IE-TAX-28471', 'IE', DATE '2021-10-05', 'LOW', 'ACTIVE', DATE '2026-08-31');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000010', 'Meridian Capital Partners', 'PRIVATE_BANKING', 'US-TAX-90312', 'US', DATE '2017-04-12', 'HIGH', 'ACTIVE', DATE '2026-08-25');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000011', 'Anke Vermeer', 'RETAIL', 'NL-TAX-40556', 'NL', DATE '2022-08-19', 'LOW', 'ACTIVE', DATE '2026-09-02');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000012', 'Castellan Manufacturing SpA', 'COMMERCIAL', 'IT-TAX-88120', 'IT', DATE '2016-12-01', 'MEDIUM', 'ACTIVE', DATE '2026-08-26');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000013', 'Grace Whitaker', 'PRIVATE_BANKING', 'GB-TAX-73209', 'GB', DATE '2015-09-23', 'HIGH', 'ACTIVE', DATE '2026-08-24');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000014', 'Nils Svensson', 'RETAIL', 'SE-TAX-51287', 'SE', DATE '2023-05-16', 'LOW', 'ACTIVE', DATE '2026-09-01');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000015', 'Harborview Shipping Co', 'COMMERCIAL', 'AU-TAX-64332', 'AU', DATE '2018-02-08', 'MEDIUM', 'INACTIVE', DATE '2026-06-14');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000016', 'Isabelle Renard', 'RETAIL', 'FR-TAX-22687', 'FR', DATE '2024-01-29', 'LOW', 'ACTIVE', DATE '2026-09-02');
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000017', 'Kwan Industrial Holdings', 'COMMERCIAL', 'SG-TAX-38845', 'SG', DATE '2019-03-03', 'MEDIUM', 'ACTIVE', DATE '2026-08-29');

-- ---------------------------------------------------------------------------
-- Deliberate business-quality defects (for later Databricks DQ testing)
-- ---------------------------------------------------------------------------

-- DQ TEST CASE: ONBOARDING_DATE in the future - not physically constrained,
-- but not a valid business fact.
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000018', 'Werner Fuchs', 'RETAIL', 'DE-TAX-90410', 'DE', DATE '2027-01-15', 'LOW', 'ACTIVE', DATE '2026-09-01');

-- DQ TEST CASE: blank (whitespace-only) CUSTOMER_NAME - satisfies NOT NULL
-- but fails a real business "non-empty name" rule.
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000019', ' ', 'RETAIL', 'US-TAX-10287', 'US', DATE '2022-06-11', 'MEDIUM', 'ACTIVE', DATE '2026-08-30');

-- DQ TEST CASE: COUNTRY_CODE not a valid ISO-3166 alpha-2 code, and
-- RISK_RATING outside the expected LOW/MEDIUM/HIGH domain - neither is
-- enforced by a CHECK constraint at the source, by design.
INSERT INTO CUSTOMER_MASTER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TYPE, TAX_ID, COUNTRY_CODE, ONBOARDING_DATE, RISK_RATING, STATUS, UPDATED_DATE) VALUES ('CUST-000020', 'Oliver Bennett', 'RETAIL', 'XX-TAX-00001', 'XX', DATE '2021-12-02', 'UNKNOWN', 'ACTIVE', DATE '2026-08-30');

COMMIT;
